import type {
  Attendee,
  AuditLog,
  BehaviorEvent,
  StaffUser,
  SwingerRecord,
  VenueQR,
  Wallet,
} from '@/types/models';

const now = new Date().toISOString();

export const defaultStaffUsers: StaffUser[] = [
  {
    id: 'staff-manager-1',
    name: 'Megan Ward',
    email: 'manager@raceqr.test',
    password: 'RaceQR123',
    role: 'manager',
    permissions: ['allocate_tokens', 'export_data', 'manage_access', 'issue_swingers', 'redeem_rewards'],
  },
  {
    id: 'staff-gate-1',
    name: 'Callum Price',
    email: 'gate@raceqr.test',
    password: 'RaceQR123',
    role: 'gate',
    permissions: ['manage_access'],
  },
  {
    id: 'staff-secretary-1',
    name: 'Nina Scott',
    email: 'secretary@raceqr.test',
    password: 'RaceQR123',
    role: 'secretary',
    permissions: ['issue_swingers', 'allocate_tokens', 'manage_access'],
  },
  {
    id: 'staff-vendor-1',
    name: 'Leo Morris',
    email: 'vendor@raceqr.test',
    password: 'RaceQR123',
    role: 'vendor',
    permissions: ['redeem_rewards'],
  },
];

export const defaultVenueQRs: VenueQR[] = [
  {
    id: 'qr-new-entry',
    label: 'Entrance QR · New Registration',
    type: 'entry-new',
    location: 'Main Gate',
    description: 'New attendee sign-up for quick onboarding and wallet creation.',
    tokenReward: 0,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-returning-entry',
    label: 'Entrance QR · Returning Check-In',
    type: 'entry-returning',
    location: 'Main Gate',
    description: 'Returning attendee fast check-in.',
    tokenReward: 0,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-stables',
    label: 'Stable Visit QR',
    type: 'stables',
    location: 'Stable Block',
    description: 'Tracks stable engagement and rewards educational visits.',
    tokenReward: 5,
    accessRoles: ['owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-secretary',
    label: 'Secretary Office QR',
    type: 'secretary-office',
    location: 'Secretary Office',
    description: 'Logs owner collection and service interactions.',
    tokenReward: 2,
    accessRoles: ['owner', 'trainer', 'staff'],
  },
  {
    id: 'qr-owner-lounge',
    label: 'Owner Lounge Access QR',
    type: 'owner-lounge',
    location: 'Owner Enclosure',
    description: 'Controls exclusive owner-only area access.',
    tokenReward: 0,
    accessRoles: ['owner', 'trainer', 'staff'],
  },
  {
    id: 'qr-vendor-drinks',
    label: 'Vendor QR · Drinks',
    type: 'vendor-drinks',
    location: 'Drinks Bar',
    description: 'Redeem tokens or swinger benefits for drinks.',
    tokenReward: 0,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-vendor-snacks',
    label: 'Vendor QR · Snacks',
    type: 'vendor-snacks',
    location: 'Trackside Cafe',
    description: 'Redeem tokens for snacks or track purchases.',
    tokenReward: 0,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-survey',
    label: 'Survey / Feedback QR',
    type: 'survey',
    location: 'Grandstand Exit',
    description: 'Captures feedback and rewards survey completion.',
    tokenReward: 3,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
  {
    id: 'qr-exit',
    label: 'Exit QR',
    type: 'exit',
    location: 'South Exit',
    description: 'Logs attendee exit and completes the journey.',
    tokenReward: 0,
    accessRoles: ['guest', 'owner', 'trainer', 'stablehand', 'staff'],
  },
];

export const defaultAttendees: Attendee[] = [
  {
    id: 'att-1',
    walletId: 'wallet-1',
    registrationType: 'named',
    name: 'Charlotte Greene',
    email: 'charlotte@example.com',
    phone: '',
    role: 'owner',
    createdAt: now,
    lastCheckInAt: now,
    status: 'checked-in',
    tags: ['high-value', 'survey-opted'],
  },
  {
    id: 'att-2',
    walletId: 'wallet-2',
    registrationType: 'named',
    name: 'Adam Fox',
    email: '',
    phone: '07123 456789',
    role: 'guest',
    createdAt: now,
    lastCheckInAt: null,
    status: 'active',
    tags: ['new-visitor'],
  },
  {
    id: 'att-3',
    walletId: 'wallet-3',
    registrationType: 'anonymous',
    name: 'Anonymous Guest #102',
    email: '',
    phone: '',
    role: 'guest',
    createdAt: now,
    lastCheckInAt: now,
    status: 'checked-in',
    tags: ['anonymous'],
  },
];

export const defaultWallets: Wallet[] = [
  {
    id: 'wallet-1',
    attendeeId: 'att-1',
    balance: 24,
    tokenValue: 1,
    history: [
      {
        id: 'txn-1',
        walletId: 'wallet-1',
        attendeeId: 'att-1',
        type: 'credit',
        amount: 10,
        tokenValue: 1,
        source: 'Registration bonus',
        note: 'Welcome reward for first registration.',
        createdAt: now,
        createdBy: 'system',
      },
      {
        id: 'txn-2',
        walletId: 'wallet-1',
        attendeeId: 'att-1',
        type: 'credit',
        amount: 14,
        tokenValue: 1,
        source: 'Secretary allocation',
        note: 'Owner hospitality uplift.',
        createdAt: now,
        createdBy: 'staff-secretary-1',
      },
    ],
  },
  {
    id: 'wallet-2',
    attendeeId: 'att-2',
    balance: 8,
    tokenValue: 1,
    history: [
      {
        id: 'txn-3',
        walletId: 'wallet-2',
        attendeeId: 'att-2',
        type: 'credit',
        amount: 8,
        tokenValue: 1,
        source: 'Stable QR',
        note: 'Engagement reward bundle.',
        createdAt: now,
        createdBy: 'staff-manager-1',
      },
    ],
  },
  {
    id: 'wallet-3',
    attendeeId: 'att-3',
    balance: 3,
    tokenValue: 1,
    history: [
      {
        id: 'txn-4',
        walletId: 'wallet-3',
        attendeeId: 'att-3',
        type: 'credit',
        amount: 3,
        tokenValue: 1,
        source: 'Survey QR',
        note: 'Anonymous feedback incentive.',
        createdAt: now,
        createdBy: 'system',
      },
    ],
  },
];

export const defaultBehaviorEvents: BehaviorEvent[] = [
  {
    id: 'evt-1',
    attendeeId: 'att-1',
    attendeeName: 'Charlotte Greene',
    qrId: 'qr-returning-entry',
    qrLabel: 'Entrance QR · Returning Check-In',
    actionType: 'check-in',
    timestamp: now,
    tokenDelta: 0,
    notes: 'Returning owner checked in at main gate.',
  },
  {
    id: 'evt-2',
    attendeeId: 'att-1',
    attendeeName: 'Charlotte Greene',
    qrId: 'qr-secretary',
    qrLabel: 'Secretary Office QR',
    actionType: 'qr-scan',
    timestamp: now,
    tokenDelta: 2,
    notes: 'Owner visited secretary office.',
    handledByStaffId: 'staff-secretary-1',
  },
  {
    id: 'evt-3',
    attendeeId: 'att-3',
    attendeeName: 'Anonymous Guest #102',
    qrId: 'qr-survey',
    qrLabel: 'Survey / Feedback QR',
    actionType: 'qr-scan',
    timestamp: now,
    tokenDelta: 3,
    notes: 'Feedback captured at exit.',
  },
];

export const defaultSwingers: SwingerRecord[] = [
  {
    id: 'swinger-1',
    attendeeId: 'att-1',
    attendeeName: 'Charlotte Greene',
    issuedByStaffId: 'staff-secretary-1',
    issuedAt: now,
    rewardType: 'drink',
    tokenValue: 6,
    redeemedAt: null,
    redeemedByStaffId: null,
    status: 'issued',
  },
];

export const defaultAuditLogs: AuditLog[] = [
  {
    id: 'audit-1',
    actorId: 'staff-manager-1',
    actorName: 'Megan Ward',
    actorRole: 'manager',
    action: 'login',
    targetType: 'auth',
    targetId: 'staff-manager-1',
    details: 'Manager authenticated for event day operations.',
    createdAt: now,
  },
  {
    id: 'audit-2',
    actorId: 'staff-secretary-1',
    actorName: 'Nina Scott',
    actorRole: 'secretary',
    action: 'allocate_tokens',
    targetType: 'wallet',
    targetId: 'wallet-1',
    details: 'Allocated 14 owner hospitality tokens.',
    createdAt: now,
  },
];
